version: '3'
services:
  db:
    image: postgres
  server:
    build: .
    command: bundle exec rails s -p 3001 -b 0.0.0.0
    volumes:
      - .:/railsapp
    ports:
      - 3001:3001
    depends_on:
      - db
  client:
    build: ./client
    command: yarn start
    volumes:
      - ./client:/reactapp
    ports:
      - 3000:3000
    links:
      - server
